### ISSUE TITLE
Central Berlin Airport

### ISSUE THREAD

**Issue by highattack30** [X-Plane/xptools#1]
I have got this message when I try to import apt file which I downloaded from the net
the apt.adt " could not be imported illegal version

I

850 Version

1     123.5 0 0 BER1 Berlin Leipziger Platz

102 H1 52.50942910 13.37750440 266.00 10.00 10.00  1 0 0 0.25 0 
14 52.50911960 13.37612820 326 0 Panoramapunkt view Kohlhoffturm

15 52.51643020 13.37876090 263.00 Pariser Platz

15 52.51976420 13.37201300 090.00 Bundestag

15 52.51863650 13.39952510 329.00 Lustgarten

15 52.51351760 13.39298940 356.00 Gendarmenmarkt

15 52.49911930 13.39169620 356.00 Mehringplatz

15 52.50616560 13.37550500 015.00 Tilla-Durieux-Park

15 52.50752030 13.37320750 176.00 Marlene-Dietrich-Platz

15 52.51412270 13.34678080 084.00 Siegessaule

1    368.70 0 0 BER2 Teufelsberg

102 H1 52.49757000 13.24100100 360.00 10.06 10.06 1 0 1 0.25 1

**Comment by mroe1** [comment]
Hello highattack30,
1. the official bug report side is here :
https://gateway.x-plane.com/bugs/
2. to the issue :
The header is wrong . Tolerated by X-plane for some reason.
On x-plane.org the author stated the package was developed for X-Plane 9 .

Anyhow , remove the blank line after 'I' and the file will load.

**Comment by bsupnik** [comment]
Hi Y'all,

Everything mroe says is 100% correct!

There's one detail to note: X-Plane parses this file because X-Plane is 
extremely loose about line endings (cr vs lf vs crlf vs lfcrcrcrlf or 
whatever crazy thing you make up).

After trying a lot of different text-handling strategies over the years, 
we (LR) eventually came up with this idea:

- Accept both CR and LF as a return character.
- Accept ANY NUMBER of CR and LF in a row as a single fused "new line".
- NEVER have a file format that depends on a blank line or the number of 
blank lines in the format.

The header is officially spec'd to have no blank lines, so only CRLF is 
legal for an "I" header file, but in practice X-Plane will tolerate any 
level of white-space crazy.

So there might be a WED todo here to intentionally match X-Plane's goofy 
rules so that anything that X-Plane can open will work.

This case really starts to matter when a file gets CR/LF converted a few 
times and you get things like the pasted file, with an extra blank line 
after every line.  This can happen when CR is turned into LF, giving you 
double-LF.

cheers
Ben
