### ISSUE TITLE
LLBG Airport Customazie Not Orginal

### ISSUE THREAD

**Issue by highattack30** [X-Plane/xptools#2]
well I download before few minutes airport called LLBG , I check the directory and the there is not earth.wed.xml and when loading the apt.dat the wed crashing I am speaking on the latest wed

WED151R1

**Comment by mroe1** [comment]
Hello highattack30,

Again , PLEASE file your bugreport here :
https://gateway.x-plane.com/bugs/

And if you do so :
since your download source is unknown , 
please attach a link and the affected apt.dat there.

BTW:
earth.wed.xml is  a project file . It is not needed for XPlane itself.
Ask the original author of the package.

**Comment by nubbix** [comment]
Hi, think you sent this to the wrong person
Have a nice dayTom

Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: highattack30 <notifications@github.com> Date: 23/10/2016  12:18  (GMT+01:00) To: X-Plane/xptools <xptools@noreply.github.com> Subject: [X-Plane/xptools] LLBG Airport Customazie Not Orginal (#2) 
well I download before few minutes airport called LLBG , I check the directory and the there is not earth.wed.xml and when loading the apt.dat the wed crashing I am speaking on the latest wed

WED151R1

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/X-Plane/xptools","title":"X-Plane/xptools","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/X-Plane/xptools"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"LLBG Airport Customazie Not Orginal (#2)"}],"action":{"name":"View Issue","url":"https://github.com/X-Plane/xptools/issues/2"}}}
